---
name: Test role

on: [pull_request]

jobs:
  molecule:
    name: Runs molecule for the ansible role
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"

      - name: Test
        uses: robertdebock/molecule-action@2.6.16
